import React, { useState, useEffect, useRef, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Calendar, ChevronRight, Loader2, Sparkles, FileText } from 'lucide-react';
import Header from '../components/Header';
import { auth, googleProvider } from '../firebase';
import { signInWithPopup, signOut, onAuthStateChanged } from 'firebase/auth';

const ArticleList = () => {
    const [allArticles, setAllArticles] = useState([]);
    const [displayedArticles, setDisplayedArticles] = useState([]);
    const [loading, setLoading] = useState(true);
    const [user, setUser] = useState(null);
    const [hasMore, setHasMore] = useState(true);
    
    const observer = useRef();
    const ITEMS_PER_PAGE = 30;

    // Auth listener (Simplified for Header support)
    useEffect(() => {
        const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
            setUser(currentUser);
        });
        return () => unsubscribe();
    }, []);

    const handleLogin = async () => {
        try {
            await signInWithPopup(auth, googleProvider);
        } catch (error) {
            console.error("Login failed:", error);
        }
    };

    const handleLogout = async () => {
        try {
            await signOut(auth);
        } catch (error) {
            console.error("Logout failed:", error);
        }
    };

    // Infinite Scroll Observer Callback
    const lastArticleRef = useCallback(node => {
        if (loading) return;
        if (observer.current) observer.current.disconnect();
        
        observer.current = new IntersectionObserver(entries => {
            if (entries[0].isIntersecting && hasMore) {
                setDisplayedArticles(prev => {
                    const currentLen = prev.length;
                    const nextLen = currentLen + ITEMS_PER_PAGE;
                    const nextBatch = allArticles.slice(0, nextLen);
                    
                    if (nextLen >= allArticles.length) {
                        setHasMore(false);
                    }
                    return nextBatch;
                });
            }
        });
        
        if (node) observer.current.observe(node);
    }, [loading, hasMore, allArticles]);

    useEffect(() => {
        const fetchArticles = async () => {
            const BASE_URL = import.meta.env.PROD
                ? 'https://raw.githubusercontent.com/jet23058/TrendGuard/data'
                : '/data';

            try {
                // Fetch the index file generated by backend
                const res = await fetch(`${BASE_URL}/articles_index.json`);
                if (res.ok) {
                    let data = await res.json();
                    
                    // Sort by date descending (Newest first)
                    data.sort((a, b) => new Date(b.date) - new Date(a.date));
                    
                    setAllArticles(data);
                    setDisplayedArticles(data.slice(0, ITEMS_PER_PAGE));
                    if (data.length <= ITEMS_PER_PAGE) {
                        setHasMore(false);
                    }
                } else {
                    console.error("Failed to fetch article index");
                }
            } catch (err) {
                console.error("Error fetching articles:", err);
            } finally {
                setLoading(false);
            }
        };

        fetchArticles();
    }, []);

    if (loading) {
        return (
            <div className="min-h-screen bg-gray-950 flex items-center justify-center text-white">
                <Loader2 className="w-8 h-8 animate-spin text-blue-500 mr-2" />
                載入文章列表...
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-950 text-gray-300 font-sans flex flex-col">
            <Header user={user} onLogin={handleLogin} onLogout={handleLogout} />

            <div className="max-w-4xl mx-auto px-4 pt-10 flex-grow w-full">
                <header className="mb-10 text-center border-b border-gray-800 pb-10">
                    <h1 className="text-3xl font-bold text-white mb-2 flex items-center justify-center gap-2">
                        <FileText className="text-blue-500" /> 每日盤勢重點
                    </h1>
                    <p className="text-gray-500">掌握每日台股動態，AI 深度解讀市場趨勢</p>
                </header>

                {displayedArticles.length === 0 ? (
                    <div className="text-center py-20 text-gray-600">
                        尚無文章資料
                    </div>
                ) : (
                    <div className="flex flex-col gap-4">
                        {displayedArticles.map((article, index) => {
                            const isLast = index === displayedArticles.length - 1;
                            return (
                                <Link
                                    ref={isLast ? lastArticleRef : null}
                                    key={article.date}
                                    to={`/report/${article.date}`}
                                    className="block group"
                                >
                                    <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden hover:border-blue-500/50 hover:shadow-lg hover:shadow-blue-900/10 transition-all duration-300">
                                        <div className="p-6 flex flex-col md:flex-row md:items-center gap-6">
                                            {/* Date Badge */}
                                            <div className="flex-shrink-0 flex md:flex-col items-center justify-center gap-2 md:gap-1 text-gray-500 md:w-24 md:border-r md:border-gray-800 md:pr-6">
                                                <Calendar size={20} className="text-blue-500 md:mb-2" />
                                                
                                                {/* Mobile Display: YYYY-MM-DD */}
                                                <span className="font-mono font-bold text-lg text-gray-300 md:hidden">
                                                    {article.date}
                                                </span>

                                                {/* Desktop Display: Year \n Month-Day */}
                                                <div className="hidden md:flex flex-col items-center">
                                                    <span className="text-xs text-gray-500 font-mono leading-none mb-1">{article.date.split('-')[0]}</span>
                                                    <span className="text-xl font-bold text-white font-mono leading-none">{article.date.substring(5)}</span>
                                                </div>
                                            </div>

                                            {/* Content */}
                                            <div className="flex-grow min-w-0">
                                                <h2 className="text-xl font-bold text-white mb-2 group-hover:text-blue-400 transition-colors truncate">
                                                    {article.title}
                                                </h2>
                                                <p className="text-sm text-gray-400 line-clamp-2 leading-relaxed">
                                                    {article.preview}
                                                </p>
                                            </div>

                                            {/* Action Icon */}
                                            <div className="flex-shrink-0 hidden md:flex items-center text-blue-500 group-hover:translate-x-1 transition-transform">
                                                <ChevronRight size={24} />
                                            </div>
                                        </div>
                                    </div>
                                </Link>
                            );
                        })}
                        
                        {hasMore && (
                            <div className="py-8 text-center text-gray-500 flex justify-center">
                                <Loader2 className="w-6 h-6 animate-spin" />
                            </div>
                        )}
                        
                        {!hasMore && displayedArticles.length > 0 && (
                            <div className="py-8 text-center text-gray-600 text-sm">
                                已顯示所有文章
                            </div>
                        )}
                    </div>
                )}
            </div>

            {/* Footer */}
            <footer className="border-t border-gray-800 bg-gray-900 py-12 text-center text-gray-600 text-xs mt-12">
                <div className="max-w-2xl mx-auto px-4 space-y-4">
                    <div className="flex justify-center gap-6 mb-4">
                        <Link to="/privacy" className="hover:text-gray-400">隱私權政策</Link>
                        <Link to="/terms" className="hover:text-gray-400">使用條款</Link>
                    </div>
                    <p>&copy; {new Date().getFullYear()} TrendGuard. All rights reserved.</p>
                </div>
            </footer>
        </div>
    );
};

export default ArticleList;
