import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Calendar, ChevronRight, Loader2, Sparkles, FileText } from 'lucide-react';
import Header from '../components/Header';
import { auth, googleProvider } from '../firebase';
import { signInWithPopup, signOut, onAuthStateChanged } from 'firebase/auth';

const ArticleList = () => {
    const [articles, setArticles] = useState([]);
    const [loading, setLoading] = useState(true);
    const [user, setUser] = useState(null);

    // Auth listener (Simplified for Header support)
    useEffect(() => {
        const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
            setUser(currentUser);
        });
        return () => unsubscribe();
    }, []);

    const handleLogin = async () => {
        try {
            await signInWithPopup(auth, googleProvider);
        } catch (error) {
            console.error("Login failed:", error);
        }
    };

    const handleLogout = async () => {
        try {
            await signOut(auth);
        } catch (error) {
            console.error("Logout failed:", error);
        }
    };

    useEffect(() => {
        const fetchArticles = async () => {
            const BASE_URL = import.meta.env.PROD
                ? 'https://raw.githubusercontent.com/jet23058/TrendGuard/data'
                : '/data';

            try {
                // Fetch the index file generated by backend
                const res = await fetch(`${BASE_URL}/articles_index.json`);
                if (res.ok) {
                    const data = await res.json();
                    setArticles(data);
                } else {
                    console.error("Failed to fetch article index");
                }
            } catch (err) {
                console.error("Error fetching articles:", err);
            } finally {
                setLoading(false);
            }
        };

        fetchArticles();
    }, []);

    if (loading) {
        return (
            <div className="min-h-screen bg-gray-950 flex items-center justify-center text-white">
                <Loader2 className="w-8 h-8 animate-spin text-blue-500 mr-2" />
                載入文章列表...
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-950 text-gray-300 font-sans pb-10">
            <Header user={user} onLogin={handleLogin} onLogout={handleLogout} />

            <div className="max-w-7xl mx-auto px-4 pt-10">
                <header className="mb-10 text-center border-b border-gray-800 pb-10">
                    <h1 className="text-3xl font-bold text-white mb-2 flex items-center justify-center gap-2">
                        <FileText className="text-blue-500" /> 每日盤勢重點
                    </h1>
                    <p className="text-gray-500">掌握每日台股動態，AI 深度解讀市場趨勢</p>
                </header>

                {articles.length === 0 ? (
                    <div className="text-center py-20 text-gray-600">
                        尚無文章資料
                    </div>
                ) : (
                    <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
                        {articles.map((article) => (
                            <Link
                                key={article.date}
                                to={`/report/${article.date}`}
                                className="block break-inside-avoid-column group"
                            >
                                <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-hidden hover:border-blue-500/50 hover:shadow-lg hover:shadow-blue-900/10 transition-all duration-300">
                                    <div className="p-6">
                                        <div className="flex items-center justify-between mb-4">
                                            <div className="text-xs font-mono text-gray-500 flex items-center gap-1">
                                                <Calendar size={12} /> {article.date}
                                            </div>
                                            {article.isAiGenerated && (
                                                <div className="flex items-center gap-1 text-[10px] bg-purple-900/30 text-purple-300 px-2 py-0.5 rounded-full border border-purple-800/50">
                                                    <Sparkles size={10} /> AI Analysis
                                                </div>
                                            )}
                                        </div>

                                        <h2 className="text-xl font-bold text-white mb-3 group-hover:text-blue-400 transition-colors line-clamp-2 leading-relaxed">
                                            {article.title}
                                        </h2>

                                        <p className="text-sm text-gray-400 mb-6 line-clamp-3 leading-relaxed">
                                            {article.preview}
                                        </p>

                                        <div className="flex items-center text-blue-500 text-sm font-bold group-hover:translate-x-1 transition-transform">
                                            閱讀完整報告 <ChevronRight size={16} />
                                        </div>
                                    </div>
                                </div>
                            </Link>
                        ))}
                    </div>
                )}
            </div>
        </div>
    );
};

export default ArticleList;
